server:
  context-path: /uaa

hystrix:
  #shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500000

spring:
  application:
    name: movingDemoOpenAPI
  output:
    ansi:
      enabled: always
  session:
    store-type: redis
  datasource:
    jndi-name: jdbc/dataSource

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:11111/eureka
      
security:
  user:
    password: password
  oauth2:
    client:
      client-id: movingdemo-users
      client-secret: users-secret
      scope: read,write
      auto-approve-scopes: '.*'
      access-token-uri: http://localhost:8888/uaa/oauth/token
      user-authorization-uri: http://localhost:8888/uaa/oauth/authorize
    resource:
      user-info-uri: http://localhost:8888/uaa/me

debug: false      
logging:
  level:
    org.springframework.security.web.util: info
    org.springframework.security: info
    org.springframework.web.servlet: info
    org.springframework.cache: info
    com.lambdaworks.redis: info
    com.lambdaworks.redis.protocol: info
    com.lambdaworks.redis.RedisChannelHandler: info
    org.springframework.security.oauth2.client.filter: info
    org.springframework.http.client: info
    org.springframework.security.oauth2.client: info
    org.springframework.session: info
    
    
    
    
      
      